//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public class PersonViewModel
{

    public int PersonId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public bool IsAuthorised { get; set; }

    public int ColourId { get; set; }

    public string ColourName { get; set; }

}

